version: "3.7"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  catalog:
    build:
      context: ./catalog
    ports:
      - "9001:9001"
    depends_on:
      - kafka
    environment:
      CATALOG_BASE_URL: "http://localhost:9001"
      AUTH_SERVICE_BASE_URL: "http://localhost:9000"
    networks:
      - app-network

  user:
    build:
      context: ./user
    ports:
      - "9000:9000"
    depends_on:
      - kafka
    environment:
      CATALOG_BASE_URL: "http://localhost:9001"
      AUTH_SERVICE_BASE_URL: "http://localhost:9000"
    networks:
      - app-network

  order:
    build:
      context: ./order
    ports:
      - "9002:9002"
    depends_on:
      - kafka
    environment:
      CATALOG_BASE_URL: "http://localhost:9001"
      AUTH_SERVICE_BASE_URL: "http://localhost:9000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge